//! Finding skills on disk, and refusing the ones Smith cannot vouch for.
//!
//! A skill lives at `<root>/skills/<name>/SKILL.md`. The *directory* names the
//! skill; frontmatter never does. Two reasons, both structural. A name that can
//! only be read by opening the body cannot appear in an index whose whole
//! purpose is to be built without opening bodies. And a project skill that
//! could name itself could aim its shadowing at a user skill whose name the
//! reader never sees anywhere in the path — the directory listing would say
//! `helper` while the catalog entry it displaced said `deploy`.
//!
//! Everything here reads; nothing here decides. A workspace body arrives with
//! the project's recorded trust status attached and is admitted, withheld, or
//! shadowed by the resolver — but it is always returned, because a skill that
//! silently does not exist is indistinguishable from one that was withheld.
//!
//! A file this module cannot use is excluded and named. It is never a reason to
//! refuse to start: a stray editor backup under `.smith/skills/` must not be
//! able to lock a user out of their own project.

use std::fs;
use std::path::{Path, PathBuf};

use agent_runtime::ability::Skill;
use agent_runtime::ability::descriptor::ContextCost;
use sha2::{Digest, Sha256};
use smith_config::trust::{ContentDigest, Executable, ExecutableKind, TrustStatus, TrustStore};

use super::{SmithSkillSources, validate_name};

/// The directory, under a state root, that holds skill directories.
const SKILLS_DIR: &str = "skills";

/// The one file that makes a directory a skill.
const BODY_FILE: &str = "SKILL.md";

/// How many skills one layer may contribute.
///
/// A bound rather than a limit anyone should reach: it exists so a directory
/// generated by accident cannot make host start unbounded.
const MAX_SKILLS_PER_LAYER: usize = 256;

/// How large a body may be, in bytes.
///
/// Independent of the runtime's later context bound, which cannot help here:
/// this one is about how much Smith is willing to read at start.
const MAX_BODY_BYTES: u64 = 1024 * 1024;

/// How many lines the frontmatter may span before parsing gives up.
const MAX_FRONT_MATTER_LINES: usize = 64;

/// How long an indexed description may be.
///
/// The description is the only text retrieval scores against, so an unbounded
/// one is a free slot in every index Smith builds.
const MAX_DESCRIPTION_CHARS: usize = 1024;

/// A skill file Smith found and could not use, kept for a surface to show.
///
/// Held rather than logged on purpose. A problem that only reaches a log is
/// exactly the failure this module exists to prevent: the user watches a skill
/// they wrote do nothing, and nothing tells them why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillProblem {
    /// The skill's directory name, which is how the user will look for it.
    pub name: String,
    /// The path that was rejected.
    pub path: PathBuf,
    /// Why it was rejected, in one bounded sentence.
    pub reason: String,
}

impl SkillProblem {
    fn new(name: impl Into<String>, path: impl Into<PathBuf>, reason: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
            reason: reason.into(),
        }
    }
}

/// One skill read from disk, pinned to the bytes that were read.
#[derive(Debug, Clone)]
pub struct DiscoveredSkill {
    /// The declaration, already pinned to the discovered content.
    pub skill: Skill,
    /// Where the body lives.
    pub path: PathBuf,
    /// The body's identity as project trust spells it.
    ///
    /// The same bytes the activation pin covers, under the framing the trust
    /// store uses. Both are computed from one read, so a decision cannot come
    /// to cover content the pin does not.
    pub content: ContentDigest,
}

impl DiscoveredSkill {
    /// The skill's name, which is its directory's name.
    pub fn name(&self) -> &str {
        &self.skill.name
    }
}

/// What one layer's directory yielded.
#[derive(Debug, Clone, Default)]
pub struct DiscoveredSkills {
    /// Usable declarations, ordered by name.
    pub skills: Vec<DiscoveredSkill>,
    /// Files that were found and refused, ordered by name.
    pub problems: Vec<SkillProblem>,
}

/// Reads `<root>/skills/`, returning what is usable and what is not.
///
/// A missing directory is not a problem and creates nothing: most users have no
/// skills, and a harness that mkdir's its way through someone's home directory
/// to find that out is a harness that leaves litter.
pub fn discover(root: &Path) -> DiscoveredSkills {
    let directory = root.join(SKILLS_DIR);
    let mut found = DiscoveredSkills::default();
    let Ok(entries) = fs::read_dir(&directory) else {
        return found;
    };

    // Sorted before anything is read, so which skills fall outside the count
    // bound is a property of the directory rather than of the order the
    // filesystem happened to hand entries back in.
    let mut candidates = entries
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_ok_and(|kind| kind.is_dir()))
        .map(|entry| entry.file_name())
        .collect::<Vec<_>>();
    candidates.sort();

    let dropped = candidates.len().saturating_sub(MAX_SKILLS_PER_LAYER);
    for entry in candidates.into_iter().take(MAX_SKILLS_PER_LAYER) {
        let name = entry.to_string_lossy().into_owned();
        let path = directory.join(&entry).join(BODY_FILE);
        // A directory without a body is not a broken skill; it is not a skill.
        // Reporting it would turn every `skills/.git` and every scratch folder
        // into a warning the user has to learn to scroll past.
        if !path.is_file() {
            continue;
        }
        match read_skill(&name, &path) {
            Ok(skill) => found.skills.push(skill),
            Err(reason) => found.problems.push(SkillProblem::new(name, path, reason)),
        }
    }
    if dropped > 0 {
        found.problems.push(SkillProblem::new(
            format!("{dropped} beyond the limit"),
            directory,
            format!(
                "only the first {MAX_SKILLS_PER_LAYER} skill directories are read, \
                 so {dropped} were not"
            ),
        ));
    }
    found
}

/// Folds discovered user and workspace skills onto `base`.
///
/// The one composition path both Smith hosts use, so the interactive TUI and
/// `smith -p` cannot index different catalogs from the same disk.
pub fn discover_into(
    base: SmithSkillSources,
    user_root: &Path,
    project: &Path,
    trust: &TrustStore,
) -> (SmithSkillSources, Vec<SkillProblem>) {
    let mut sources = base;
    let mut problems = Vec::new();

    let user = discover(user_root);
    problems.extend(user.problems);
    for found in user.skills {
        sources = sources.with_user(found.skill);
    }

    let workspace = discover(&project.join(".smith"));
    problems.extend(workspace.problems);
    for found in workspace.skills {
        match workspace_trust(project, trust, &found) {
            Ok(status) => sources = sources.with_workspace(found.skill, status),
            Err(reason) => {
                problems.push(SkillProblem::new(found.skill.name, found.path, reason));
            }
        }
    }

    problems.sort_by(|left, right| left.name.cmp(&right.name));
    (sources, problems)
}

/// The project's recorded decision about exactly this body.
///
/// [`Executable::from_file`] supplies the two properties this must not
/// re-derive: a project-relative label, so a rewritten skill is recognizably
/// the same skill at a new digest rather than an unrelated one, and a refusal
/// for a path resolving outside the project — a symlink under `.smith/skills/`
/// aimed at a user skill would otherwise launder that skill into the workspace
/// layer, where it could shadow the very skill it points at.
///
/// Its digest is compared against the one discovery read. They differ only if
/// the file changed between the two reads, and a decision about content Smith
/// no longer holds authorizes nothing.
fn workspace_trust(
    project: &Path,
    trust: &TrustStore,
    found: &DiscoveredSkill,
) -> Result<TrustStatus, String> {
    let executable = Executable::from_file(project, ExecutableKind::Skill, &found.path)
        .map_err(|error| error.message)?;
    if executable.digest() != &found.content {
        return Err("its content changed while it was being read".to_owned());
    }
    trust
        .status(project, &executable)
        .map_err(|error| error.message)
}

/// Reads and validates one body, returning a declaration pinned to its bytes.
fn read_skill(name: &str, path: &Path) -> Result<DiscoveredSkill, String> {
    validate_name(name).map_err(|error| error.message)?;

    let size = fs::metadata(path)
        .map_err(|error| format!("it cannot be read: {error}"))?
        .len();
    if size > MAX_BODY_BYTES {
        return Err(format!(
            "it is {size} bytes, over the {MAX_BODY_BYTES}-byte limit for a skill body"
        ));
    }
    let bytes = fs::read(path).map_err(|error| format!("it cannot be read: {error}"))?;
    let text = std::str::from_utf8(&bytes)
        .map_err(|_| "it is not UTF-8, so its instructions cannot be read".to_owned())?;

    let front_matter = parse_front_matter(text)?;
    if let Some(declared) = &front_matter.name
        && declared != name
    {
        return Err(format!(
            "its frontmatter calls it `{declared}`, but a skill is named by its \
             directory; rename the directory or the field so they agree"
        ));
    }
    if front_matter.body.trim().is_empty() {
        return Err("it has no instructions after its frontmatter".to_owned());
    }

    let skill = Skill::from_verified_file(
        name,
        front_matter.description,
        path,
        Sha256::digest(&bytes).into(),
    )
    // The estimate the index would otherwise have to guess at. Discovery has
    // the body in hand, so a file-backed skill's advertised cost is measured
    // rather than assumed, and descriptor resolution still reads nothing.
    .with_metadata(
        "smith.instruction_tokens",
        ContextCost::estimate("", front_matter.body)
            .instruction_tokens
            .to_string(),
    );
    Ok(DiscoveredSkill {
        skill,
        path: path.to_path_buf(),
        content: ContentDigest::of(&bytes),
    })
}

/// The interpreted frontmatter fields, and the instructions after them.
struct FrontMatter<'a> {
    name: Option<String>,
    description: String,
    body: &'a str,
}

/// Parses the leading `---` block.
///
/// The grammar is narrower than YAML on purpose: `---`, then `key: value`
/// lines, then `---`. A file that parses here parses the same way anywhere, and
/// a skill cannot reach Smith's policy through a YAML feature nobody meant to
/// support. Keys other than `name` and `description` are ignored rather than
/// rejected, so a skill authored for another tool loads without importing that
/// tool's schema — and are not retained, so no file-authored key reaches a
/// descriptor.
fn parse_front_matter(text: &str) -> Result<FrontMatter<'_>, String> {
    let mut rest = strip_line(text, "---").ok_or_else(|| {
        "it does not start with a `---` frontmatter block declaring a `description`".to_owned()
    })?;

    let mut name = None;
    let mut description = None;
    for number in 1..=MAX_FRONT_MATTER_LINES {
        let Some((line, tail)) = next_line(rest) else {
            break;
        };
        rest = tail;
        if line.trim_end() == "---" {
            let description = description
                .ok_or_else(|| "its frontmatter declares no `description`".to_owned())?;
            return Ok(FrontMatter {
                name,
                description,
                body: rest,
            });
        }
        if line.trim().is_empty() {
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            return Err(format!("its frontmatter line {number} is not `key: value`"));
        };
        let value = value.trim();
        match key.trim() {
            "name" => name = Some(value.to_owned()),
            "description" => {
                if value.is_empty() {
                    return Err("its `description` is empty".to_owned());
                }
                if value.chars().count() > MAX_DESCRIPTION_CHARS {
                    return Err(format!(
                        "its `description` is longer than {MAX_DESCRIPTION_CHARS} characters"
                    ));
                }
                description = Some(value.to_owned());
            }
            _ => {}
        }
    }
    Err(format!(
        "its frontmatter is not closed with `---` within {MAX_FRONT_MATTER_LINES} lines"
    ))
}

/// `text` past a leading `line` and its terminator, if it starts with one.
fn strip_line<'a>(text: &'a str, line: &str) -> Option<&'a str> {
    let rest = text.strip_prefix(line)?;
    rest.strip_prefix("\r\n")
        .or_else(|| rest.strip_prefix('\n'))
}

/// The next line of `text` without its terminator, and everything after it.
fn next_line(text: &str) -> Option<(&str, &str)> {
    if text.is_empty() {
        return None;
    }
    match text.find('\n') {
        Some(end) => Some((text[..end].trim_end_matches('\r'), &text[end + 1..])),
        None => Some((text, "")),
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use agent_runtime::ability::activation::Activated;
    use smith_config::trust::TrustDecision;
    use tempfile::TempDir;

    use super::*;
    use crate::skills::SmithSkillLayer;

    /// A state root with `skills/<name>/SKILL.md` written for each entry.
    fn root_with(entries: &[(&str, &str)]) -> TempDir {
        let root = tempfile::tempdir().expect("a temporary root");
        for (name, body) in entries {
            write_skill(root.path(), name, body);
        }
        root
    }

    fn write_skill(root: &Path, name: &str, body: &str) -> PathBuf {
        let directory = root.join(SKILLS_DIR).join(name);
        fs::create_dir_all(&directory).expect("a skill directory");
        let path = directory.join(BODY_FILE);
        fs::write(&path, body).expect("a skill body");
        path
    }

    const REVIEW: &str =
        "---\ndescription: Review Rust boundaries\n---\n\nRead the unsafe blocks first.\n";

    #[test]
    fn directory_name_is_the_skill_name() {
        let root = root_with(&[("rust-review", REVIEW)]);
        let found = discover(root.path());
        assert!(found.problems.is_empty(), "{:?}", found.problems);
        assert_eq!(found.skills.len(), 1);
        assert_eq!(found.skills[0].name(), "rust-review");
        assert_eq!(found.skills[0].skill.description, "Review Rust boundaries");
    }

    #[test]
    fn frontmatter_name_mismatch_is_a_problem_and_registers_nothing() {
        let root = root_with(&[(
            "rust-review",
            "---\nname: deploy\ndescription: Review Rust boundaries\n---\n\nBody.\n",
        )]);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert_eq!(found.problems.len(), 1);
        assert_eq!(found.problems[0].name, "rust-review");
        assert!(found.problems[0].reason.contains("`deploy`"));
    }

    #[test]
    fn frontmatter_name_matching_the_directory_is_accepted() {
        let root = root_with(&[(
            "rust-review",
            "---\nname: rust-review\ndescription: Review Rust boundaries\n---\n\nBody.\n",
        )]);
        let found = discover(root.path());
        assert!(found.problems.is_empty(), "{:?}", found.problems);
        assert_eq!(found.skills.len(), 1);
    }

    #[test]
    fn missing_description_is_a_problem_and_the_others_still_load() {
        let root = root_with(&[
            ("good", REVIEW),
            (
                "no-description",
                "---\nname: no-description\n---\n\nBody.\n",
            ),
            ("also-good", REVIEW),
        ]);
        let found = discover(root.path());
        assert_eq!(
            found
                .skills
                .iter()
                .map(DiscoveredSkill::name)
                .collect::<Vec<_>>(),
            ["also-good", "good"]
        );
        assert_eq!(found.problems.len(), 1);
        assert_eq!(found.problems[0].name, "no-description");
        assert!(found.problems[0].reason.contains("description"));
    }

    #[test]
    fn unknown_frontmatter_keys_are_ignored() {
        let root = root_with(&[(
            "ported",
            "---\nname: ported\ndescription: Ported from another tool\nlicense: MIT\n\
             allowed-tools: Read, Edit\n---\n\nBody.\n",
        )]);
        let found = discover(root.path());
        assert!(found.problems.is_empty(), "{:?}", found.problems);
        assert_eq!(found.skills.len(), 1);
        assert!(
            !found.skills[0].skill.metadata.contains_key("license"),
            "a file-authored key reached the declaration"
        );
    }

    #[test]
    fn body_without_frontmatter_is_a_problem() {
        let root = root_with(&[("bare", "Just some instructions.\n")]);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert!(found.problems[0].reason.contains("`---`"));
    }

    #[test]
    fn frontmatter_without_instructions_is_a_problem() {
        let root = root_with(&[("empty", "---\ndescription: Does nothing\n---\n\n   \n")]);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert!(found.problems[0].reason.contains("no instructions"));
    }

    #[test]
    fn oversized_body_is_reported_not_truncated() {
        let root = tempfile::tempdir().expect("a temporary root");
        let body = format!(
            "---\ndescription: Large\n---\n\n{}",
            "x".repeat(usize::try_from(MAX_BODY_BYTES).expect("a usize") + 1)
        );
        write_skill(root.path(), "large", &body);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert!(found.problems[0].reason.contains("over the"));
    }

    #[test]
    fn oversized_description_is_reported() {
        let root = tempfile::tempdir().expect("a temporary root");
        let body = format!(
            "---\ndescription: {}\n---\n\nBody.\n",
            "d".repeat(MAX_DESCRIPTION_CHARS + 1)
        );
        write_skill(root.path(), "wordy", &body);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert!(found.problems[0].reason.contains("longer than"));
    }

    #[test]
    fn per_layer_count_bound_reports_what_it_dropped() {
        let root = tempfile::tempdir().expect("a temporary root");
        for index in 0..MAX_SKILLS_PER_LAYER + 3 {
            write_skill(root.path(), &format!("skill-{index:04}"), REVIEW);
        }
        let found = discover(root.path());
        assert_eq!(found.skills.len(), MAX_SKILLS_PER_LAYER);
        assert_eq!(found.problems.len(), 1);
        assert!(found.problems[0].reason.contains("so 3 were not"));
    }

    #[test]
    fn invalid_directory_name_is_reported() {
        let root = root_with(&[("my skill", REVIEW)]);
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert_eq!(found.problems[0].name, "my skill");
        assert!(found.problems[0].reason.contains("ASCII"));
    }

    #[test]
    fn loose_file_and_bodyless_directory_are_skipped_silently() {
        let root = root_with(&[("real", REVIEW)]);
        fs::write(root.path().join(SKILLS_DIR).join("README.md"), "notes").expect("a loose file");
        fs::create_dir_all(root.path().join(SKILLS_DIR).join("scratch")).expect("a directory");
        let found = discover(root.path());
        assert_eq!(found.skills.len(), 1);
        assert!(found.problems.is_empty(), "{:?}", found.problems);
    }

    #[test]
    fn missing_skills_directory_creates_nothing() {
        let root = tempfile::tempdir().expect("a temporary root");
        let found = discover(root.path());
        assert!(found.skills.is_empty());
        assert!(found.problems.is_empty());
        assert!(
            !root.path().join(SKILLS_DIR).exists(),
            "discovery created the directory it was looking for"
        );
    }

    #[test]
    fn discovery_pins_the_bytes_it_read() {
        let root = root_with(&[("rust-review", REVIEW)]);
        let found = discover(root.path());
        let resolved = SmithSkillSources::new()
            .with_user(found.skills[0].skill.clone())
            .resolve()
            .expect("the declaration resolves");
        assert_eq!(
            resolved.abilities()[0]
                .materialize()
                .expect("the pinned body"),
            Activated::SkillInstructions(REVIEW.into())
        );

        fs::write(
            &found.skills[0].path,
            "---\ndescription: Review\n---\n\nSwapped.\n",
        )
        .expect("rewrite the body");
        assert!(
            resolved.abilities()[0].materialize().is_err(),
            "a rewritten body activated against a pin taken from other bytes"
        );
    }

    /// A project and the user state root that holds decisions about it.
    struct Workspace {
        project: TempDir,
        user: TempDir,
    }

    impl Workspace {
        fn new() -> Self {
            Self {
                project: tempfile::tempdir().expect("a project"),
                user: tempfile::tempdir().expect("a user root"),
            }
        }

        fn store(&self) -> TrustStore {
            TrustStore::open(self.user.path()).expect("a trust store")
        }

        fn write_project_skill(&self, name: &str, body: &str) -> PathBuf {
            write_skill(&self.project.path().join(".smith"), name, body)
        }

        fn resolve(
            &self,
            trust: &TrustStore,
        ) -> (crate::skills::ResolvedSmithSkills, Vec<SkillProblem>) {
            let (sources, problems) = discover_into(
                SmithSkillSources::new(),
                self.user.path(),
                self.project.path(),
                trust,
            );
            (sources.resolve().expect("the catalog resolves"), problems)
        }
    }

    #[test]
    fn untrusted_project_skill_is_indexed_inert_and_does_not_shadow() {
        let workspace = Workspace::new();
        workspace.write_project_skill("rust-review", REVIEW);
        write_skill(
            workspace.user.path(),
            "rust-review",
            "---\ndescription: Review Rust boundaries\n---\n\nUSER BODY\n",
        );

        let (resolved, problems) = workspace.resolve(&workspace.store());
        assert!(problems.is_empty(), "{problems:?}");
        let workspace_entry = resolved
            .index()
            .iter()
            .find(|entry| entry.layer == SmithSkillLayer::Workspace)
            .expect("the project skill is indexed");
        assert!(!workspace_entry.activatable);
        assert_eq!(resolved.abilities().len(), 1);
        assert_eq!(
            resolved.abilities()[0]
                .materialize()
                .expect("the user body"),
            Activated::SkillInstructions(
                "---\ndescription: Review Rust boundaries\n---\n\nUSER BODY\n".into()
            )
        );
    }

    #[test]
    fn approved_project_skill_activates_the_reviewed_digest() {
        let workspace = Workspace::new();
        let path = workspace.write_project_skill("rust-review", REVIEW);
        let mut trust = workspace.store();
        let executable =
            Executable::from_file(workspace.project.path(), ExecutableKind::Skill, &path)
                .expect("the skill is project content");
        trust
            .record(workspace.project.path(), &executable, TrustDecision::Allow)
            .expect("the decision records");

        let (resolved, problems) = workspace.resolve(&trust);
        assert!(problems.is_empty(), "{problems:?}");
        assert!(resolved.index().iter().all(|entry| entry.activatable));
        assert_eq!(
            resolved.abilities()[0].materialize().expect("the body"),
            Activated::SkillInstructions(REVIEW.into())
        );
    }

    #[test]
    fn edited_project_skill_reports_changed_not_trusted() {
        let workspace = Workspace::new();
        let path = workspace.write_project_skill("rust-review", REVIEW);
        let mut trust = workspace.store();
        let executable =
            Executable::from_file(workspace.project.path(), ExecutableKind::Skill, &path)
                .expect("the skill is project content");
        trust
            .record(workspace.project.path(), &executable, TrustDecision::Allow)
            .expect("the decision records");

        fs::write(
            &path,
            "---\ndescription: Review Rust boundaries\n---\n\nEDITED\n",
        )
        .expect("a later commit rewrites it");
        let (resolved, _) = workspace.resolve(&trust);
        let entry = resolved
            .index()
            .iter()
            .find(|entry| entry.layer == SmithSkillLayer::Workspace)
            .expect("the project skill is indexed");
        assert!(!entry.activatable);
        assert!(resolved.abilities().is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_project_skill_out_of_root_is_refused() {
        let workspace = Workspace::new();
        let outside = tempfile::tempdir().expect("somewhere else");
        let target = outside.path().join("SKILL.md");
        fs::write(&target, REVIEW).expect("a body outside the project");
        let directory = workspace.project.path().join(".smith/skills/borrowed");
        fs::create_dir_all(&directory).expect("a skill directory");
        std::os::unix::fs::symlink(&target, directory.join(BODY_FILE)).expect("a symlink");

        let (resolved, problems) = workspace.resolve(&workspace.store());
        assert!(resolved.index().is_empty(), "the escape was indexed");
        assert_eq!(problems.len(), 1);
        assert_eq!(problems[0].name, "borrowed");
        assert!(problems[0].reason.contains("outside the project"));
    }
}
